### ISSUE TITLE
Missing config and documentation

### ISSUE THREAD

**Issue by richhalliwell** [nigelsdtech/node-book-virgin-active-class#1]
Great script - but it's missing a bunch of config referenced in 
Could you stub this config so it can be more easily recreated?

Also - i think this script is triggered when it receives an email. not clear if that could contain an invalid date, or a future date (To allow the system to poll until the class becomes available) or the format of the email required

nice stable virginactiveClass.js library though

**Comment by nigelsdtech** [comment]
Hey there,

I didn't put too much effort into the readme as I didn't think there was much of a market for it. It was more for my own use.

I'll try to get an example together for basic config setup. Regarding the email trigger - I've setup a repeating reminder in my google calendar. Therefore I get an email in my inbox that says something like "Book Yoga for next Tuesday" at 7am on a Tuesday. The script is configured to check my inbox on Tuesday for an email with this title, and book a specified class one week later (Virgin opens bookings for their classes at 7am a week before).

**Comment by richhalliwell** [comment]
Hi Nigel.
Calendar reminder makes sense - although i'm still not sure I understand the credential store parts that need configuring. I couldn't find any model examples here

**Comment by richhalliwell** [comment]
Could you share an example of your credentials client_secret.json

**Comment by nigelsdtech** [comment]
Hey Rich,

I've updated the README to give instructions on how to set up the script. Have a read and see if it helps. It will show you how to set up the client secrets and various other credentials.

Let me know how it goes.

**Comment by richhalliwell** [comment]
hi Nigel

this is mch better - although i'm still getting quite stuck here in the setup instructios: Setup your credentials 
I think some of the steps within google cloud compute and the api manager might have changed. There might be a missing step in adding the app before gmail will let the user create a app specific password
